name: Ruff CI

on:
  pull_request:

jobs:
  ruff-checks:
    name: ruff-checks
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: install-ruff
        run: pip install ruff

      - name: ruff-lint
        run: ruff check .

      - name: ruff-format
        run: ruff format --check .